# Generated by Django 6.0.6 on 2026-06-16 22:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abbonamento",
            fields=[
                (
                    "id_abbonamento",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "descrizione",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("durata", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AllergiaIntolleranza",
            fields=[
                (
                    "id_allergia",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=30)),
                ("descrizione", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria_alimento",
            fields=[
                (
                    "id_categoria",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Giornata_tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_giorno", models.CharField(blank=True, max_length=20)),
                ("calorie_target", models.DecimalField(decimal_places=2, max_digits=6)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrizionista",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("cf", models.CharField(max_length=16)),
                ("nome", models.CharField(max_length=30)),
                ("cognome", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=255)),
                ("sesso", models.CharField(max_length=1)),
                ("eta", models.IntegerField()),
                ("n_albo", models.CharField(max_length=20)),
                ("specializzazione", models.CharField(max_length=100)),
                ("stato", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Alimento",
            fields=[
                (
                    "id_alimento",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=50)),
                ("selezionabile", models.BooleanField()),
                ("carboidrati", models.DecimalField(decimal_places=2, max_digits=5)),
                ("proteine", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grassi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("calorie", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "restrizioni",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.categoria_alimento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pasto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("orario_consigliato", models.TimeField()),
                (
                    "calorie_totali",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "proteine_totali",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "carboidrati_totali",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "grassi_totali",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "giornata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pasti",
                        to="NutriCare.giornata_tipo",
                    ),
                ),
            ],
            options={
                "ordering": ["orario_consigliato"],
            },
        ),
        migrations.CreateModel(
            name="Paziente",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("cf", models.CharField(max_length=16)),
                ("nome", models.CharField(max_length=30)),
                ("cognome", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=255)),
                ("sesso", models.CharField(max_length=1)),
                ("eta", models.IntegerField()),
                ("note_cliniche", models.TextField(blank=True, null=True)),
                (
                    "allergie",
                    models.ManyToManyField(
                        blank=True, to="NutriCare.allergiaintolleranza"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Acquisto",
            fields=[
                (
                    "id_acquisto",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("data_acquisto", models.DateField()),
                ("prezzo_pagato", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pagamento", models.CharField(max_length=50)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("coppia", models.BooleanField(default=False)),
                (
                    "abbonamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.abbonamento",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="NutriCare.paziente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbbonamentoAttivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inizio", models.DateField(auto_now_add=True)),
                ("data_fine", models.DateField()),
                ("attivo", models.BooleanField(default=True)),
                (
                    "abbonamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.abbonamento",
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.paziente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piano_alimentare",
            fields=[
                (
                    "id_piano_alimentare",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("data_inizio", models.DateField()),
                ("data_fine", models.DateField(blank=True, null=True)),
                ("stato", models.CharField(max_length=20)),
                ("obiettivo", models.CharField(max_length=100)),
                (
                    "nutrizionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.nutrizionista",
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.paziente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="giornata_tipo",
            name="piano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="giornate",
                to="NutriCare.piano_alimentare",
            ),
        ),
        migrations.CreateModel(
            name="Listino_prezzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_listino_prezzo", models.CharField(max_length=10)),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_inizio_validita", models.DateField()),
                ("data_fine_validita", models.DateField(blank=True, null=True)),
                (
                    "abbonamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.abbonamento",
                    ),
                ),
            ],
            options={
                "unique_together": {("abbonamento", "data_inizio_validita")},
            },
        ),
        migrations.CreateModel(
            name="Inclusione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grammatura", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="NutriCare.alimento",
                    ),
                ),
                (
                    "pasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inclusioni",
                        to="NutriCare.pasto",
                    ),
                ),
            ],
            options={
                "unique_together": {("pasto", "alimento")},
            },
        ),
        migrations.CreateModel(
            name="Effettuare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.acquisto",
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.paziente",
                    ),
                ),
            ],
            options={
                "unique_together": {("paziente", "acquisto")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="giornata_tipo",
            unique_together={("piano", "n_giorno")},
        ),
        migrations.CreateModel(
            name="Recensione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inserimento", models.DateTimeField(auto_now_add=True)),
                (
                    "stelle",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("commento", models.CharField(max_length=500)),
                (
                    "nutrizionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.nutrizionista",
                    ),
                ),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.paziente",
                    ),
                ),
            ],
            options={
                "unique_together": {("paziente", "nutrizionista")},
            },
        ),
        migrations.CreateModel(
            name="Rilevazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_rilevazione", models.DateField()),
                ("altezza", models.DecimalField(decimal_places=2, max_digits=5)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "perc_massa_grassa",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("commento", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "paziente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.paziente",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_rilevazione"],
                "unique_together": {("paziente", "data_rilevazione")},
            },
        ),
        migrations.CreateModel(
            name="Scatenare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.alimento",
                    ),
                ),
                (
                    "allergia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="NutriCare.allergiaintolleranza",
                    ),
                ),
            ],
            options={
                "unique_together": {("alimento", "allergia")},
            },
        ),
    ]
