# Generated by Django 6.0.6 on 2026-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NutriCare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisto",
            name="sconto_utilizzato",
            field=models.BooleanField(default=False),
        ),
    ]
