# Generated by Django 6.0.6 on 2026-06-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NutriCare", "0002_acquisto_sconto_utilizzato"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Abbonamento",
            new_name="Abbonamenti",
        ),
        migrations.RenameModel(
            old_name="AbbonamentoAttivo",
            new_name="AbbonamentiAttivi",
        ),
        migrations.RenameModel(
            old_name="Acquisto",
            new_name="Acquisti",
        ),
        migrations.RenameModel(
            old_name="Alimento",
            new_name="Alimenti",
        ),
        migrations.RenameModel(
            old_name="AllergiaIntolleranza",
            new_name="AllergieIntolleranze",
        ),
        migrations.RenameModel(
            old_name="Categoria_alimento",
            new_name="Categorie_alimenti",
        ),
        migrations.RenameModel(
            old_name="Giornata_tipo",
            new_name="Giornate_tipo",
        ),
        migrations.RenameModel(
            old_name="Listino_prezzi",
            new_name="Listini_prezzi",
        ),
        migrations.RenameModel(
            old_name="Nutrizionista",
            new_name="Nutrizionisti",
        ),
        migrations.RenameModel(
            old_name="Pasto",
            new_name="Pasti",
        ),
        migrations.RenameModel(
            old_name="Paziente",
            new_name="Pazienti",
        ),
        migrations.RenameModel(
            old_name="Piano_alimentare",
            new_name="Piani_alimentari",
        ),
        migrations.RenameModel(
            old_name="Recensione",
            new_name="Recensioni",
        ),
        migrations.RenameModel(
            old_name="Rilevazione",
            new_name="Rilevazioni",
        ),
    ]
